# Programming for Data Science 2024
## Homework Assigment Two
Homework activities aim at testing not only your ability to put into practice the concepts you have learned during the Lectures and Labs, but also your ability to explore the Python documentation as a resource. Above all, it is an opportunity for you to challenge yourself and practice. If you are having difficulties with the assignment reach out for support using moodle's Discussion Forum.

### Description

This homework assignment will test your capacity to **load and manipulate data with Pandas**. 
    
The goal is to develop intuition on filtering, arranging, and merging data, which will be useful for the next homework assignment.<br/>
Fill the empty cells with your code and deliver a copy of this notebook to Moodle. <br/>
    
Your submission will be graded according to the following guidelines:
1. **Execution** (does your program does what is asked from the exercise?
2. **Objectivity** (are you using the adequate libraries? are you using a library ... )
3. **Readability** of your code (including comments, variables naming, supporting text, etc ...)

**Comment your code properly**, which includes naming your variables in a meaningful manner. **Badly documented code will be penalized.**

This assignment is to be done in pairs, and remember that you can't have the same pair from the previous and subsequent assignments.

**Students that are caught cheating will obtain a score of 0 points.** <br>

Homework 2 is worth 25% of your final grade.    

The submission package should correspond to a .zip archive (.rar files are not accepted) with the following files:
1. Jupyter Notebook with the output of all the cells;
2. HTML print of your Jupyter Notebook (in Jupyter go to File -> Download as -> HTML);
3. All text or .csv files that are exported as part of the exercises. **Please don't upload the files downloaded/imported as part of the exercises.**

**Please change the name of the notebook to "H2.\<student_1_id\>_\<student_2_id\>.ipynb", replacing \<student_id\> by your student_id.** <br>

Submission is done through the respective Moodle activity, and only one of the group members should submit the files. <br>
The deadline is the **19th of October at 12:00**. <br>
A penalty of 1 point per day late will be applied to late deliveries. <br>
**In this notebook, you are allowed to use Pandas and Numpy.**

In [1]:
import numpy as np
import scipy
import pandas as pd

# <span style="color:brown"> Start Here </span> 

[Please Complete the following form with your details]

Student Name - Diogo Ruivo <br>
Student id - 20240584 <br>
Contact e-mail - 20240584@novaims.unl.pt <br>


Student Name - José Tiago <br>
Student id - 20240582 <br>
Contact e-mail - 20240582@novaims.unl.pt <br>

# <span style="color:brown"> Part 1 - Get the Data </span>

## Download and Load the World Development Indicators Dataset

We will work with the **World Development Indicators dataset**, which should be downloaded from the world bank data catalog.<br/>
Hence, the first step is to unzip the data given on Moodle, you can do this by running the cell below. <br/>

In [2]:
import zipfile, io

z = zipfile.ZipFile("WDI_csv.zip")
z.extractall()

del z

*The above code downloads a zip archive to the working folder, which by default is the the location of this notebook in your computer. <br/>
Secondly, and since the document downloaded is a zip archive, it extracts the documents from the archive. <br/> 
The contents include multiple .csv files, however we will be working only with the document 'WDICSV.csv'. <br/>*

**1.** In the cell bellow, use Pandas to open the file "WDICSV.csv" and **save** it to a variable called **wdi**.<br/>

In [3]:
import pandas as pd

# Load the CSV file into a DataFrame
wdi = pd.read_csv("WDICSV.csv")

**2.** Check the top of the dataframe to ensure it was loaded correctly.

In [4]:
#To show the first few rows of the DataFrame
wdi.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,17.401410,17.911234,18.463874,18.924037,19.437054,20.026254,20.647969,21.165877,21.863139,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.728819,7.005877,7.308571,7.547226,7.875917,8.243018,8.545483,8.906711,9.261320,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.080931,38.422282,38.722108,38.993157,39.337872,39.695279,40.137847,40.522209,41.011132,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.860474,33.903800,38.854624,40.199898,43.017148,44.381259,46.264875,48.100862,48.711995,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,17.619475,16.500171,24.605861,25.396929,27.037528,29.137914,31.001049,32.777910,33.747907,NaN

## Download and Load the Penn World Table V9.0

We will additionally use data from the pwt v9.0 tables. <br/> 

**Run the following cell to download the dataset**.

In [5]:
import urllib
urllib.request.urlretrieve("https://www.rug.nl/ggdc/docs/pwt90.xlsx", "pwt90.xlsx")

('pwt90.xlsx', <http.client.HTTPMessage at 0x1c31d3bc110>)

**3.** In the following cell, open and read the file 'pwt90.xlsx' and **save** it into variable **pwt**. <br/>

In [6]:
# Load pwt90.xlsx file into a DataFrame
pwt = pd.read_excel('pwt90.xlsx', sheet_name ='Data')

**4.** Check the top of the dataframe to ensure it was loaded correctly.

In [7]:
# To show the first few rows
pwt.head(10)

,countrycode,country,currency_unit,year,rgdpe,rgdpo,pop,emp,avh,hc,...,csh_g,csh_x,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_k
0,ABW,Aruba,Aruban Guilder,1950,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABW,Aruba,Aruban Guilder,1951,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABW,Aruba,Aruban Guilder,1952,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABW,Aruba,Aruban Guilder,1953,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABW,Aruba,Aruban Guilder,1954,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ABW,Aruba,Aruban Guilder,1955,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ABW,Aruba,Aruban Guilder,1956,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ABW,Aruba,Aruban Guilder,1957,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ABW,Aruba,Aruban Guilder,1958,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,ABW,Aruba,Aruban Guilder,1959,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# <span style="color:brown"> Part 2 - Data Processing </span>

## Data Wrangling

Now that we have loaded our data we are ready to start playing with it. <br/>

**5.** Start by printing all the column values in the cell bellow.

In [8]:
# Print column names for the World Development Indicators dataset
print("WDI Data Columns:")
print(wdi.columns)

# Print column names for the Penn World Table dataset
print("\nPWT Data Columns:")
print(pwt.columns)

WDI Data Columns:
Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023'],
      dtype='object')

PWT Data Columns:
Index(['countrycode', 'country', 'currency_unit', 'year', 'rgdpe', 'rgdpo',
       'pop', 'emp', 'avh', 'hc', 'ccon', 'cda', 'cgdpe', 'cgdpo', 'ck',
       'ctfp', 'cwtfp', 'rgdpna', 'rconna', 'rdana', 'rkna', 'rtfpna',
       'rwtfpna', 'labsh', 'delta', 'xr', 'pl_con', 'pl_da', 'pl_gdpo',
       'i_cig', 'i_xm', 'i_xr', 'i_outlier', 'cor_exp', 'statcap', 'csh_c',
       'csh_i', 'csh_g', 'csh_x', 'csh_m', 'csh_r', 'pl_c', 'pl_i', 'pl_g',
       'pl_x', 'pl_m', 'pl_k'],
      dtype='object')

**6.** List the values in the column 'Country Name'.You will get a list with repeated values, **delete all duplicates** to ease your analysis. <br/>

*Tip: There is a method in the pandas library that allows to do this easily.*

In [9]:
# List all values in the 'Country Name' column including duplicates
wdi['Country Name']

0         Africa Eastern and Southern
1         Africa Eastern and Southern
2         Africa Eastern and Southern
3         Africa Eastern and Southern
4         Africa Eastern and Southern
                     ...
395803                       Zimbabwe
395804                       Zimbabwe
395805                       Zimbabwe
395806                       Zimbabwe
395807                       Zimbabwe
Name: Country Name, Length: 395808, dtype: object

In [10]:
## Removing duplicates
print(wdi['Country Name'].drop_duplicates().tolist())

['Africa Eastern and Southern', 'Africa Western and Central', 'Arab World', 'Caribbean small states', 'Central Europe and the Baltics', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (excluding high income)', 'East Asia & Pacific (IDA & IBRD countries)', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (excluding high income)', 'Europe & Central Asia (IDA & IBRD countries)', 'European Union', 'Fragile and conflict affected situations', 'Heavily indebted poor countries (HIPC)', 'High income', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Late-demographic dividend', 'Latin America & Caribbean', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Least developed countries: UN classification', 'Low & middle income', 'Low income', 'Lower middle income', 'Middle East & North Africa', 'Middle East & North Africa (excluding high income)', 'Middle East & North Africa (IDA & IBRD countries)', 'Middle income', 'North America', 'Not classified', 'OECD members', 'Other small states', 'Pacific island small states', 'Post-demographic dividend', 'Pre-demographic dividend', 'Small states', 'South Asia', 'South Asia (IDA & IBRD)', 'Sub-Saharan Africa', 'Sub-Saharan Africa (excluding high income)', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Upper middle income', 'World', 'Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Martin (French part)', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

You might notice that while the bottom rows represent Countries, the top rows represent aggregates of countries (e.g., world regions). <br/> We are only interested in **working with country-level data**, and as such we need to filter out all the unnecessary rows.

**7.** Save all the values of column 'Country Name' in a variable called **cnames**. <br/>r/>

In [11]:
# Save all 'Country Name' in a new variable: cnames
cnames = wdi['Country Name'].values
cnames

array(['Africa Eastern and Southern', 'Africa Eastern and Southern',
       'Africa Eastern and Southern', ..., 'Zimbabwe', 'Zimbabwe',
       'Zimbabwe'], dtype=object)

**7.1.** Delete all duplicate values.<br>

In [12]:
# wdi['Country Name'].unique() will remove duplicates from the 'cnames' array
cnames = wdi['Country Name'].unique()
cnames

array(['Africa Eastern and Southern', 'Africa Western and Central',
       'Arab World', 'Caribbean small states',
       'Central Europe and the Baltics', 'Early-demographic dividend',
       'East Asia & Pacific',
       'East Asia & Pacific (excluding high income)',
       'East Asia & Pacific (IDA & IBRD countries)', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia (IDA & IBRD countries)', 'European Union',
       'Fragile and conflict affected situations',
       'Heavily indebted poor countries (HIPC)', 'High income',
       'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only',
       'IDA total', 'Late-demographic dividend',
       'Latin America & Caribbean',
       'Latin America & Caribbean (excluding high income)',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Least developed countries: UN classification',
       'Low & middle income', 'Low income', 'Lower middle income',
       'Middle East & North Africa',
       'Middle East & North Africa (excluding high income)',
       'Middle East & North Africa (IDA & IBRD countries)',
       'Middle income', 'North America', 'Not classified', 'OECD members',
       'Other small states', 'Pacific island small states',
       'Post-demographic dividend', 'Pre-demographic dividend',
       'Small states', 'South Asia', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Upper middle income',
       'World', 'Afghanistan', 'Albania', 'Algeria', 'American Samoa',
       'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
       'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Faroe Islands', 'Fiji',
       'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia, The',
       'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland',
       'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq',
       'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo', 'Kuwait',
       'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mexico', 'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Romania',
       'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia',
       'St. Martin (French part)', 'St. Vincent and the Grenadines',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand',
       'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela, RB', 'Viet Nam', 'Virgin Islands (U.S.)',
       'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe'],
      dtype=object)

**7.2.** Print the names that do not represent countries.

In [13]:
# Get all names before 'Afghanistan', which represent aggregates (not countries)
cnames[:cnames.tolist().index('Afghanistan')]

array(['Africa Eastern and Southern', 'Africa Western and Central',
       'Arab World', 'Caribbean small states',
       'Central Europe and the Baltics', 'Early-demographic dividend',
       'East Asia & Pacific',
       'East Asia & Pacific (excluding high income)',
       'East Asia & Pacific (IDA & IBRD countries)', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia (IDA & IBRD countries)', 'European Union',
       'Fragile and conflict affected situations',
       'Heavily indebted poor countries (HIPC)', 'High income',
       'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only',
       'IDA total', 'Late-demographic dividend',
       'Latin America & Caribbean',
       'Latin America & Caribbean (excluding high income)',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Least developed countries: UN classification',
       'Low & middle income', 'Low income', 'Lower middle income',
       'Middle East & North Africa',
       'Middle East & North Africa (excluding high income)',
       'Middle East & North Africa (IDA & IBRD countries)',
       'Middle income', 'North America', 'Not classified', 'OECD members',
       'Other small states', 'Pacific island small states',
       'Post-demographic dividend', 'Pre-demographic dividend',
       'Small states', 'South Asia', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Upper middle income',
       'World'], dtype=object)

You can take advantage of the structure of the dataset to realize that aggregates (Continents, Regions, etc) are all located on the top of the series 'cnames'. Moreover, since the series is small you can easily validate this assumption manually and then use that information to extract a slice of all the entries that represent non-countries entities.<br/>

**8.** In the next cell filter out, from **wdi**, the rows in which 'Country Name' represents an aggregate of countries.<br/>

In [14]:
# This will filter out rows that represent aggregates
wdi = wdi.drop(wdi[wdi.index < wdi[wdi['Country Name'] == 'Afghanistan'].index[0]].index)

**9.** Check that the top of the **wdi** dataframe now only has countries and not aggregates of countries.

In [15]:
wdi.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
72912,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,NaN
72913,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,NaN
72914,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.0,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85.0,NaN
72915,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,NaN
72916,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,NaN

**10.** Reset the indexes of **wdi**. Perform this operation in-place.

In [16]:
wdi.reset_index(drop=True, inplace=True)

**11.** Show that the indexes have been reseted.

In [17]:
wdi.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,NaN
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,NaN
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,78.0,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85.0,NaN
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,NaN
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,NaN

In [18]:
wdi.tail()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
322891,Zimbabwe,ZWE,Women who believe a husband is justified in be...,SG.VAW.REFU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,14.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322892,Zimbabwe,ZWE,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.700000,NaN,NaN,NaN,5.40000,NaN,NaN,NaN,NaN
322893,Zimbabwe,ZWE,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,32.400000,NaN,NaN,NaN,33.70000,NaN,NaN,NaN,NaN
322894,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,59.606951,59.740456,59.888983,60.053623,60.216147,60.37761,60.551609,60.69318,60.825294,NaN
322895,Zimbabwe,ZWE,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,NaN,NaN,NaN,NaN,NaN,...,18000.000000,16000.000000,14000.000000,11000.000000,8400.000000,6900.00000,5900.000000,5200.00000,4900.000000,NaN

*Note that when reseting the index, pandas appends a new column at the begining of the data frame, which holds the previous index values.*

## Indicator Codes and Indicator Names

**12.** Select the columns 'Indicator Name' and 'Indicator Code'.Then, delete all the duplicates, and print the top 5 and bottom 5 values. <br/>

*Note: You should be able to do everything in a single line of code for the top 5 values and a single line for the bottom 5 values.*

In [19]:
# the top 5 values
print(wdi[['Indicator Name', 'Indicator Code']].drop_duplicates().head())

# the bottom 5 values
print(wdi[['Indicator Name', 'Indicator Code']].drop_duplicates().tail())

                                      Indicator Name     Indicator Code
0  Access to clean fuels and technologies for coo...     EG.CFT.ACCS.ZS
1  Access to clean fuels and technologies for coo...  EG.CFT.ACCS.RU.ZS
2  Access to clean fuels and technologies for coo...  EG.CFT.ACCS.UR.ZS
3            Access to electricity (% of population)     EG.ELC.ACCS.ZS
4  Access to electricity, rural (% of rural popul...  EG.ELC.ACCS.RU.ZS
                                         Indicator Name     Indicator Code
1483  Women who believe a husband is justified in be...     SG.VAW.REFU.ZS
1484  Women who were first married by age 15 (% of w...  SP.M15.2024.FE.ZS
1485  Women who were first married by age 18 (% of w...  SP.M18.2024.FE.ZS
1486  Women's share of population ages 15+ living wi...  SH.DYN.AIDS.FE.ZS
1487  Young people (ages 15-24) newly infected with HIV     SH.HIV.INCD.YG

**13.** Create a new DataFrame named **indicators** made up of the columns 'Indicator Name' and 'Indicator Code'. Then, delete all the duplicated entries. Finally, set the column 'Indicator Code' as the index of **indicators**. 

*Note: Try to perform all these steps in a single line of code.*

In [20]:
# Create a new DataFrame 'indicators' containing only 'Indicator Name' and 'Indicator Code', remove duplicates, and set 'Indicator Code' as the index
indicators = wdi[['Indicator Name', 'Indicator Code']].drop_duplicates().set_index('Indicator Code')

**The 'indicators' DataFrame can operate now as a dictionary. <br/>**
By passing an 'Indicator Code' (key) it returns the associated 'Indicator Name' (value).<br/>

**14.** Using the **indicators** DataFrame, find the 'Indicator Code' associated with the following observables:
1. 'Population', find the 'Indicator Code' of the total population in a country;
2. 'GDP', find the GDP measured in current US Dollars;
3. 'GINI index'

*Hint: You can use the method STRING.str.contains('substring') to check whether a string contains a substring.*

In [21]:
#1. Find the Indicator Code associated with Population, total
population_code = indicators[indicators['Indicator Name'].str.contains('Population, total')].index
print("Indicator Code 'Population':", population_code)

Indicator Code 'Population': Index(['SP.POP.TOTL'], dtype='object', name='Indicator Code')

In [22]:
#2.Indicator Code' associated with 'GDP (current US$)
gdp_code = indicators[indicators['Indicator Name'].str.contains(r'GDP \(current US\$\)')].index
print("Indicator Code for GDP (current US$):", gdp_code)

Indicator Code for GDP (current US$): Index(['NY.GDP.MKTP.CD'], dtype='object', name='Indicator Code')

In [23]:
#3.To the Indicator Code where Indicator Name contains GINI index
gini_code = indicators[indicators['Indicator Name'].str.contains('Gini index')].index
print("Indicator Code for Gini index:", gini_code)

Indicator Code for Gini index: Index(['SI.POV.GINI'], dtype='object', name='Indicator Code')

## Extracting and Cleaning Data from WDI and PWT

**15.** From **wdi** extract the columns 'Indicator Code', 'Country Code', and '2012'.
Save the output in variable **wdi_sample**.

*Note: You should be able to perfom all operations in a single line of code. <br/>*

In [24]:
# Extract the columns 'Indicator Code', 'Country Code', and '2012' in one line and save to wdi_sample
wdi_sample = wdi[['Indicator Code', 'Country Code', '2012']]
wdi_sample

           Indicator Code Country Code          2012
0          EG.CFT.ACCS.ZS          AFG     22.900000
1       EG.CFT.ACCS.RU.ZS          AFG      8.000000
2       EG.CFT.ACCS.UR.ZS          AFG     74.300000
3          EG.ELC.ACCS.ZS          AFG     69.100000
4       EG.ELC.ACCS.RU.ZS          AFG     60.800000
...                   ...          ...           ...
322891     SG.VAW.REFU.ZS          ZWE           NaN
322892  SP.M15.2024.FE.ZS          ZWE           NaN
322893  SP.M18.2024.FE.ZS          ZWE           NaN
322894  SH.DYN.AIDS.FE.ZS          ZWE     59.241862
322895     SH.HIV.INCD.YG          ZWE  21000.000000

[322896 rows x 3 columns]

**16.** Select from **wdi_sample** the lines associated with the Indicator Codes that you found in question 14., which concern the data of the 'Population total','GDP', and 'GINI index'.

In [25]:
# Filter wdi_sample to select only the rows with the given indicator codes
wdi_sample = wdi_sample[wdi_sample['Indicator Code'].isin(['SP.POP.TOTL', 'NY.GDP.MKTP.CD', 'SI.POV.GINI'])]
wdi_sample

        Indicator Code Country Code          2012
473     NY.GDP.MKTP.CD          AFG  1.990733e+10
497        SI.POV.GINI          AFG           NaN
1080       SP.POP.TOTL          AFG  3.046648e+07
1961    NY.GDP.MKTP.CD          ALB  1.231983e+10
1985       SI.POV.GINI          ALB  2.900000e+01
...                ...          ...           ...
320417     SI.POV.GINI          ZMB           NaN
321000     SP.POP.TOTL          ZMB  1.474466e+07
321881  NY.GDP.MKTP.CD          ZWE  1.711485e+10
321905     SI.POV.GINI          ZWE           NaN
322488     SP.POP.TOTL          ZWE  1.326533e+07

[651 rows x 3 columns]

**17.** Create a pivot table, in which the **values** are column '2012', the **index** is 'Country Code', and the **columns** are the Indicator Codes. <br/>

*Hint: Pandas has a very useful method to create pivot tables.*

In [26]:
wdi_sample = wdi_sample.pivot_table(values='2012', index='Country Code', columns='Indicator Code')
wdi_sample

Indicator Code  NY.GDP.MKTP.CD  SI.POV.GINI  SP.POP.TOTL
Country Code
ABW               2.615208e+09          NaN     102112.0
AFG               1.990733e+10          NaN   30466479.0
AGO               1.280529e+11          NaN   25188292.0
ALB               1.231983e+10         29.0    2900401.0
AND               3.188653e+09          NaN      71013.0
...                        ...          ...          ...
XKX               6.163484e+09         29.0    1807106.0
YEM               3.540133e+10          NaN   26223391.0
ZAF               4.344005e+11          NaN   53145033.0
ZMB               2.550306e+10          NaN   14744658.0
ZWE               1.711485e+10          NaN   13265331.0

[217 rows x 3 columns]

**18.** Rename the column names of **wdi_sample** to 'Population', 'GDP', and 'GINI', accordingly.

In [27]:
# Rename the columns of wdi_sample to 'Population', 'GDP', and 'GINI'
wdi_sample.rename(columns={
    'SP.POP.TOTL': 'Population',
    'NY.GDP.MKTP.CD': 'GDP',
    'SI.POV.GINI': 'GINI'
}, inplace=True)
wdi_sample

Indicator Code           GDP  GINI  Population
Country Code
ABW             2.615208e+09   NaN    102112.0
AFG             1.990733e+10   NaN  30466479.0
AGO             1.280529e+11   NaN  25188292.0
ALB             1.231983e+10  29.0   2900401.0
AND             3.188653e+09   NaN     71013.0
...                      ...   ...         ...
XKX             6.163484e+09  29.0   1807106.0
YEM             3.540133e+10   NaN  26223391.0
ZAF             4.344005e+11   NaN  53145033.0
ZMB             2.550306e+10   NaN  14744658.0
ZWE             1.711485e+10   NaN  13265331.0

[217 rows x 3 columns]

**19.** From **pwt** select only the values of the year 2012. <br/>
Then, extract the columns 'countrycode' and 'hc' into a new variable **pwt_sample**. <br/>
Rename 'countrycode' to 'Country Code', so that it matches the same column in **wdi_sample**<br/>

*Note: in this case 'hc' stands for the Human Capital Index.<br/>*

In [28]:
## Filter pwt to keep just the rows for the year 2012
pwt = pwt[pwt['year'] == 2012]
pwt

,countrycode,country,currency_unit,year,rgdpe,rgdpo,pop,emp,avh,hc,...,csh_g,csh_x,csh_m,csh_r,pl_c,pl_i,pl_g,pl_x,pl_m,pl_k
62,ABW,Aruba,Aruban Guilder,2012,3744.970947,3576.219971,0.102393,0.048999,NaN,NaN,...,0.349973,0.658712,-0.897609,-2.205558e-04,0.843722,0.537646,0.574607,0.712659,0.659917,0.445752
127,AGO,Angola,Kwanza,2012,172309.781250,192991.562500,22.685632,7.734930,NaN,1.431295,...,0.151636,0.594577,-0.152131,-1.731410e-01,0.814157,0.626251,0.806827,0.608597,0.708104,0.494440
192,AIA,Anguilla,East Caribbean Dollar,2012,362.970490,284.968933,0.014133,NaN,NaN,NaN,...,0.247040,0.642892,-1.149568,1.991619e-16,0.905987,0.576558,0.666143,0.766684,0.574777,0.468203
257,ALB,Albania,Lek,2012,28811.394531,30245.425781,2.880667,0.918536,NaN,2.917346,...,0.219016,0.100642,-0.286791,6.482826e-02,0.474846,0.512915,0.204226,0.651857,0.567234,0.437449
322,ARE,United Arab Emirates,UAE Dirham,2012,558347.437500,609734.437500,8.952542,5.833085,NaN,2.723864,...,0.040045,0.543664,-0.501104,2.314945e-01,0.809330,0.450129,1.080167,0.645966,0.708509,0.376715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11567,VNM,Viet Nam,Dong,2012,444350.312500,446818.343750,90.335547,50.738335,2346.886529,2.532614,...,0.109613,0.368257,-0.363079,1.849865e-02,0.365370,0.388770,0.190046,0.701474,0.706825,0.288093
11632,YEM,Yemen,Yemeni Rial,2012,85529.218750,92789.835938,24.882792,5.887811,NaN,1.488720,...,0.226886,0.128504,-0.178876,-3.546018e-03,0.398928,0.454961,0.254046,0.597890,0.684820,0.305485
11697,ZAF,South Africa,Rand,2012,635144.250000,627725.187500,52.837274,16.870811,2230.199703,2.596012,...,0.186948,0.215672,-0.240848,7.603919e-03,0.629597,0.578120,0.677215,0.732109,0.690536,0.451233
11762,ZMB,Zambia,Kwacha,2012,52006.925781,50184.925781,14.786581,4.038710,NaN,2.330032,...,0.117582,0.251029,-0.263323,1.413835e-02,0.493326,0.463229,0.496555,0.746388,0.669028,0.337339
11827,ZWE,Zimbabwe,US Dollar,2012,23708.654297,24360.527344,14.565482,6.248271,NaN,2.459828,...,0.178643,0.225631,-0.479897,-7.699820e-02,0.474047,1.363167,0.458315,0.712036,0.634858,0.608320

In [29]:
# Extract the columns 'countrycode' and 'hc' into pwt_sample
pwt_sample = pwt[['countrycode', 'hc']]
pwt_sample

      countrycode        hc
62            ABW       NaN
127           AGO  1.431295
192           AIA       NaN
257           ALB  2.917346
322           ARE  2.723864
...           ...       ...
11567         VNM  2.532614
11632         YEM  1.488720
11697         ZAF  2.596012
11762         ZMB  2.330032
11827         ZWE  2.459828

[182 rows x 2 columns]

In [30]:
## Rename 'countrycode' to 'Country Code'
pwt_sample.rename(columns={'countrycode': 'Country Code'}, inplace=True)
pwt_sample

C:\Users\HP\AppData\Local\Temp\ipykernel_8708\4054841816.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pwt_sample.rename(columns={'countrycode': 'Country Code'}, inplace=True)

      Country Code        hc
62             ABW       NaN
127            AGO  1.431295
192            AIA       NaN
257            ALB  2.917346
322            ARE  2.723864
...            ...       ...
11567          VNM  2.532614
11632          YEM  1.488720
11697          ZAF  2.596012
11762          ZMB  2.330032
11827          ZWE  2.459828

[182 rows x 2 columns]

**20.** Finally, create a new dataframe named **data** that contains the columns from **wdi_sample** and **pwt_sample**, matched by 'Country Code'. 

*Hint: Use the method concat(), and make sure both dataframes have the same index ('Country Code').*

In [31]:
pwt_sample.set_index(['Country Code'], inplace=True)
data = pd.concat([wdi_sample, pwt_sample], axis = 1)

In [32]:
data

                       GDP  GINI  Population        hc
Country Code
ABW           2.615208e+09   NaN    102112.0       NaN
AFG           1.990733e+10   NaN  30466479.0       NaN
AGO           1.280529e+11   NaN  25188292.0  1.431295
ALB           1.231983e+10  29.0   2900401.0  2.917346
AND           3.188653e+09   NaN     71013.0       NaN
...                    ...   ...         ...       ...
ZMB           2.550306e+10   NaN  14744658.0  2.330032
ZWE           1.711485e+10   NaN  13265331.0  2.459828
AIA                    NaN   NaN         NaN       NaN
MSR                    NaN   NaN         NaN       NaN
TWN                    NaN   NaN         NaN  3.135961

[220 rows x 4 columns]

# <span style="color:brown"> Part 3 - Analysing a Dataset </span>

**21.** Perform the necessary manipulations to answer the following questions, unless otherwise stated you can use the country codes to represent the countries in your solutions:
1. Which countries have a **population size of 10 million habitations +/- 1 million**?
2. What is  the **average** and the **standard deviation in the GDP** for the countries listed in 1?
3. What is  the **average** and the **standard deviation in the GDP per capita** for the countries listed in 1?
4. Consider the following classification of country size: <br/>
    Tiny - population < 1 000 000 <br/>
    Very Small - 1 000 000 <= population < 5 000 000 <br/>
    Small - 5 000 000 <= population < 15 000 000 <br/>
    Medium - 15 000 000 <= population < 30 000 000 <br/>
    Large - 30 000 000 <= population < 100 000 000 <br/>
    Huge - 100 000 000 <= population <br/>
   What is  the **average** and the **standard deviation in the GDP per capita for the countries in each size classification**?   
5. Create a **function** that will take a dataframe and a column name. This function should **return** a series with binary values indicating whether the **values from the column are above the mean value of that column** (indicated with a value of 1 or 0 otherwise). If the value in the column is missing (NaN) the value in the series should also be missing (NaN). Test your function. *Hint:* search how to check if something is None so that we can return None. <br/>
6. What is the **average GDP per capita of the countries after being grouped by size classification and whether the human capital was above or below average**? *Hint: as an example, two of the groups should be (1) tiny and human capital below average, (2) tiny and human capital above average.*
7. What is the **average GDP per capita of the countries after being grouped by whether the human capital was above or below average and whether the gini coefficient was above or below average?**
8. What is the **name of the country** that has the **highest GDP per capita, a Gini coefficient below average and a level of human capital below average**?
9. What is the **name of the country** that has the **highest GDP per capita, a Gini coefficient below average for its size classification, and a level of human capital below average for its size classification**?
10. What is the **name of the country** that has the **largest % increase in GDP between 1980 and 2010?** *HINT: You will need to use the wdi dataframe.*

Write the necessary code to answer each question in a single cell. <br/>
Print the answer at the end of that cell.

In [33]:
#1
# Define the population range between 9 million and 11 million
min_population = 9_000_000
max_population = 11_000_000

# Filter the countries whose population is within this range
countries_with_population = data[(data['Population'] >= min_population) & (data['Population'] <= max_population)]

print("Countries with a population between 9 and 11 million:")
print(countries_with_population.index)

Countries with a population between 9 and 11 million:
Index(['AZE', 'BDI', 'BEN', 'BLR', 'BOL', 'CZE', 'DOM', 'GIN', 'HTI', 'HUN',
       'PRT', 'RWA', 'SSD', 'SWE'],
      dtype='object', name='Country Code')

In [34]:
#2
# Extract the GDP values for these countries
gdp_values = countries_with_population['GDP']

# Calculate the average and standard deviation of the GDP
average_gdp = gdp_values.mean()
std_dev_gdp = gdp_values.std()

print(f"Average GDP: {average_gdp}")
print(f"Standard Deviation of GDP: {std_dev_gdp}")

Average GDP: 98851409945.84126
Standard Deviation of GDP: 149245794399.39508

In [35]:
#3
# Calculate GDP per capita for these countries
gdp_per_capita = countries_with_population['GDP'] / countries_with_population['Population']

# Calculate the average and standard deviation of GDP per capita
average_gdp_per_capita = gdp_per_capita.mean()
std_dev_gdp_per_capita = gdp_per_capita.std()

print(f"Average GDP per capita: {average_gdp_per_capita}")
print(f"Standard Deviation of GDP per capita: {std_dev_gdp_per_capita}")

Average GDP per capita: 9982.440647663661
Standard Deviation of GDP per capita: 15473.789886856379

In [36]:
#4
# Define the function to classify countries based on population size
def classify_size(population):
    if population < 1_000_000:
        return 'Tiny'
    elif 1_000_000 <= population < 5_000_000:
        return 'Very Small'
    elif 5_000_000 <= population < 15_000_000:
        return 'Small'
    elif 15_000_000 <= population < 30_000_000:
        return 'Medium'
    elif 30_000_000 <= population < 100_000_000:
        return 'Large'
    else:
        return 'Huge'

# Apply the classification function to create a new column 'Size Classification'
data['Size Classification'] = data['Population'].apply(classify_size)

# Calculate GDP per capita for each country
data['GDP per Capita'] = data['GDP'] / data['Population']

# Group by 'Size Classification' and calculate average and standard deviation of GDP per capita
gdp_per_capita_stats = data.groupby('Size Classification')['GDP per Capita'].agg(['mean', 'std']).reset_index()

print(gdp_per_capita_stats)

  Size Classification          mean           std
0                Huge  14158.730825  18610.257687
1               Large  13177.431583  15611.569429
2              Medium   8903.482776  16313.630730
3               Small  16201.659272  23617.072371
4                Tiny  28226.323970  36308.718148
5          Very Small  14177.620484  18398.172964

In [37]:
#5
## Create the function
def binary_above_mean(dataframe, column_name):
    # Check if column exists in the dataframe
    if column_name not in dataframe.columns:
        raise ValueError(f"Column '{column_name}' does not exist in the dataframe.")
    
    # Calculate the mean of the column, ignoring NaN values
    column_mean = dataframe[column_name].mean()
    
    # Create a series with binary values (1 if above mean, 0 if below or equal)
    binary_series = dataframe[column_name].apply(
        lambda x: 1 if x > column_mean else (0 if not pd.isna(x) else np.nan)
    )
    
    return binary_series

# Example DataFrame to test the function
test_data = pd.DataFrame({
    'Country': ['AZE', 'BDI', 'BEN', 'BLR', 'BOL'],
    'Value': [100000, 200000, None, 50000, 30000]
})

# Test the function
binary_series = binary_above_mean(test_data, 'Value')

# Display the results
print("Original DataFrame:")
print(test_data)
print("\nBinary Series Indicating Values Above Mean:")
print(binary_series)

Original DataFrame:
  Country     Value
0     AZE  100000.0
1     BDI  200000.0
2     BEN       NaN
3     BLR   50000.0
4     BOL   30000.0

Binary Series Indicating Values Above Mean:
0    1.0
1    1.0
2    NaN
3    0.0
4    0.0
Name: Value, dtype: float64

In [38]:
data

,GDP,GINI,Population,hc,Size Classification,GDP per Capita
Country Code,,,,,,
ABW,2.615208e+09,NaN,102112.0,NaN,Tiny,25611.175767
AFG,1.990733e+10,NaN,30466479.0,NaN,Large,653.417475
AGO,1.280529e+11,NaN,25188292.0,1.431295,Medium,5083.826873
ALB,1.231983e+10,29.0,2900401.0,2.917346,Very Small,4247.631343
AND,3.188653e+09,NaN,71013.0,NaN,Tiny,44902.380766
...,...,...,...,...,...,...
ZMB,2.550306e+10,NaN,14744658.0,2.330032,Small,1729.647471
ZWE,1.711485e+10,NaN,13265331.0,2.459828,Small,1290.193957
AIA,NaN,NaN,NaN,NaN,Huge,NaN
MSR,NaN,NaN,NaN,NaN,Huge,NaN
TWN,NaN,NaN,NaN,3.135961,Huge,NaN

In [39]:
#6

# Calculate GDP per capita in the main data DataFrame
data['GDP per Capita'] = data['GDP'] / data['Population']

# Apply size classification
data['Size Classification'] = data['Population'].apply(classify_size)

# Use the binary_above_mean function to classify human capital
data['HC Classification'] = binary_above_mean(data, 'hc').apply(lambda x: 'Above Average' if x == 1 else 'Below Average')

# Average GDP per Capita grouped by Size and Human Capital Classification
average_gdp_hc = data.groupby(['Size Classification', 'HC Classification'])['GDP per Capita'].mean().reset_index()

print("Average GDP per Capita by Size and Human Capital Classification:")
print(average_gdp_hc)

Average GDP per Capita by Size and Human Capital Classification:
   Size Classification HC Classification  GDP per Capita
0                 Huge     Above Average    27900.357925
1                 Huge     Below Average     2707.374909
2                Large     Above Average    24249.265533
3                Large     Below Average     3489.576877
4               Medium     Above Average    19389.666388
5               Medium     Below Average     1413.351624
6                Small     Above Average    33815.347537
7                Small     Below Average     3872.077487
8                 Tiny     Above Average    41099.349432
9                 Tiny     Below Average    25987.536933
10          Very Small     Above Average    19135.544230
11          Very Small     Below Average     9455.788344

In [40]:
#7
# Calculate the mean human capital and Gini coefficient
mean_hc = data['hc'].mean()
mean_gini = data['GINI'].mean()

# Classify human capital status
data['HC Classification'] = binary_above_mean(data, 'hc').apply(lambda x: 'Above Average' if x == 1 else 'Below Average')

# Classify Gini status
data['GINI Classification'] = binary_above_mean(data, 'GINI').apply(lambda x: 'Above Average' if x == 1 else 'Below Average')

# Average GDP per Capita grouped by Human Capital and Gini Classification
average_gdp_combined = data.groupby(['HC Classification', 'GINI Classification'])['GDP per Capita'].mean().reset_index()

print("\nAverage GDP per Capita by Human Capital and Gini Classification:")
print(average_gdp_combined)

Average GDP per Capita by Human Capital and Gini Classification:
  HC Classification GINI Classification  GDP per Capita
0     Above Average       Above Average    13020.948708
1     Above Average       Below Average    30707.541332
2     Below Average       Above Average     3766.892210
3     Below Average       Below Average    13425.035342

In [41]:
data

,GDP,GINI,Population,hc,Size Classification,GDP per Capita,HC Classification,GINI Classification
Country Code,,,,,,,,
ABW,2.615208e+09,NaN,102112.0,NaN,Tiny,25611.175767,Below Average,Below Average
AFG,1.990733e+10,NaN,30466479.0,NaN,Large,653.417475,Below Average,Below Average
AGO,1.280529e+11,NaN,25188292.0,1.431295,Medium,5083.826873,Below Average,Below Average
ALB,1.231983e+10,29.0,2900401.0,2.917346,Very Small,4247.631343,Above Average,Below Average
AND,3.188653e+09,NaN,71013.0,NaN,Tiny,44902.380766,Below Average,Below Average
...,...,...,...,...,...,...,...,...
ZMB,2.550306e+10,NaN,14744658.0,2.330032,Small,1729.647471,Below Average,Below Average
ZWE,1.711485e+10,NaN,13265331.0,2.459828,Small,1290.193957,Below Average,Below Average
AIA,NaN,NaN,NaN,NaN,Huge,NaN,Below Average,Below Average
MSR,NaN,NaN,NaN,NaN,Huge,NaN,Below Average,Below Average
TWN,NaN,NaN,NaN,3.135961,Huge,NaN,Above Average,Below Average

In [42]:
#8
# Calculate the average Gini coefficient and human capital
avg_gini = data['GINI'].mean()
avg_hc = data['hc'].mean()

# Filter the data to only include countries with a Gini coefficient below average and a level of human capital below average
filtered_data = data[(data['GINI'] < avg_gini) & (data['hc'] < avg_hc)]

# Drop rows with missing values in Gini and hc
filtered_data = filtered_data.dropna(subset=['GINI', 'hc'])

# Sort the filtered data by GDP per capita in descending order
sorted_data = filtered_data.sort_values(by='GDP per Capita', ascending=False)

# Print the country with the highest GDP per capita
sorted_data.index[0]

'PRT'

In [43]:
#9
# Calculate the average Gini coefficient and human capital for each size classification
avg_gini_by_size = data.groupby('Size Classification')['GINI'].mean()
avg_hc_by_size = data.groupby('Size Classification')['hc'].mean()

# Filter the data to only include countries with a Gini coefficient below average and a level of human capital below average for their size classification
filtered_data = data[(data['GINI'] < data['Size Classification'].map(avg_gini_by_size)) & 
                      (data['hc'] < data['Size Classification'].map(avg_hc_by_size))]

# Drop rows with missing values in Gini and hc
filtered_data = filtered_data.dropna(subset=['GINI', 'hc'])

# Sort the filtered data by GDP per capita in descending order
sorted_data = filtered_data.sort_values(by='GDP per Capita', ascending=False)

# Print the country with the highest GDP per capita
if not sorted_data.empty:
    print(sorted_data.index[0])
else:
    print("No country meets the criteria")

IRN

In [46]:
#10
# Filter the data for GDP in 1980 and 2010
gdp_1980 = wdi[wdi['Indicator Code'] == 'NY.GDP.MKTP.CD'][['Country Code', '1980']]
gdp_2010 = wdi[wdi['Indicator Code'] == 'NY.GDP.MKTP.CD'][['Country Code', '2010']]

# Merge the GDP data for 1980 and 2010 on 'Country Code'
gdp_comparison = pd.merge(gdp_1980, gdp_2010, on='Country Code', suffixes=('_1980', '_2010'))

# Drop rows with missing GDP data for either 1980 or 2010
gdp_comparison = gdp_comparison.dropna(subset=['1980', '2010'])

# Calculate the percentage increase in GDP for each country
gdp_comparison['GDP % Increase'] = ((gdp_comparison['2010'] - gdp_comparison['1980']) / gdp_comparison['1980']) * 100

# Find the country with the largest percentage increase
largest_increase_country = gdp_comparison.loc[gdp_comparison['GDP % Increase'].idxmax()]
largest_increase_country['Country Code']

'GNQ'